repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
#
#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [python]
#        args:
#          [
#            "-rn", # Only display messages
#            "-sn", # Don't display the score
#            # Disable docstring checks and to few public methods
#            "--disable=C0114,C0115,C0116, R0903"
#          ]